import { ServiceLink, InternalTool } from './types';

export const APP_NAME = "dewey.beer";

export const HOSTED_SERVICES: ServiceLink[] = [
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    description: 'Media Server',
    url: 'https://jellyfin.dewey.beer',
    iconName: 'Film',
    color: 'text-purple-400',
    status: 'active',
  },
  {
    id: 'jellyseerr',
    name: 'Jellyseerr',
    description: 'Media Request Manager',
    url: 'https://requests.dewey.beer',
    iconName: 'Search',
    color: 'text-cyan-400',
    status: 'active',
  },
  {
    id: 'audiobookshelf',
    name: 'Audiobookshelf',
    description: 'Audiobook Server',
    url: 'https://books.dewey.beer',
    iconName: 'Headphones',
    color: 'text-emerald-400',
    status: 'active',
  },
  {
    id: 'immich',
    name: 'Immich',
    description: 'Photo Backup',
    url: 'http://immich.local',
    iconName: 'Image',
    color: 'text-violet-400',
    status: 'planned',
  },
  {
    id: 'unifi',
    name: 'Unifi Controller',
    description: 'Network Management',
    url: 'https://unifi.ui.com/',
    iconName: 'Wifi',
    color: 'text-indigo-400',
    status: 'active',
  },
  {
    id: 'adguard',
    name: 'AdGuard Home',
    description: 'Network Security',
    url: 'http://192.168.4.50:8085/',
    iconName: 'Shield',
    color: 'text-green-400',
    status: 'active',
  },
];

export const INTERNAL_TOOLS: InternalTool[] = [
  // --- Workbench ---
  {
    id: 'pizza-calculator',
    name: 'Dough Math',
    description: 'Perfect pizza dough calculator',
    path: '/tools/pizza',
    iconName: 'Pizza',
    color: 'text-orange-400',
    category: 'workbench',
    status: 'active',
  },
  // --- Web Development ---
  {
    id: 'optio',
    name: 'Optio - BC Options Manager',
    description: 'Advanced BigCommerce Option Automation',
    externalUrl: 'https://colors.dewey.beer/',
    iconName: 'Palette',
    color: 'text-pink-400',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'utm-generator',
    name: 'UTM Generator',
    description: 'Campaign Link Builder',
    path: '/tools/utm-generator',
    iconName: 'Link2',
    color: 'text-violet-400',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'squoosh',
    name: 'Squoosh',
    description: 'Image Compression Tool',
    externalUrl: 'https://squoosh.app/',
    iconName: 'Minimize2',
    color: 'text-pink-500',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'ai-upscaler',
    name: 'AI Upscaler',
    description: 'Enhance & Upscale Images',
    externalUrl: 'https://image-upscaling.net/upscaling/en.html',
    iconName: 'Maximize2',
    color: 'text-blue-500',
    category: 'web-dev',
    status: 'active',
  },
];