import { ServiceLink, InternalTool } from './types';

export const APP_NAME = "dewey.beer";

export const HOSTED_SERVICES: ServiceLink[] = [
  {
    id: 'jellyfin',
    name: 'Jellyfin',
    description: 'Media Server',
    url: 'http://jellyfin.local', // User would change this to actual IP
    iconName: 'Film',
    color: 'text-purple-400',
    status: 'active',
  },
  {
    id: 'jellyseerr',
    name: 'Jellyseerr',
    description: 'Media Request Manager',
    url: 'http://jellyseerr.local',
    iconName: 'Search',
    color: 'text-cyan-400',
    status: 'active',
  },
  {
    id: 'immich',
    name: 'Immich',
    description: 'Photo Backup',
    url: 'http://immich.local',
    iconName: 'Image',
    color: 'text-violet-400',
    status: 'planned',
  },
  {
    id: 'unifi',
    name: 'Unifi Controller',
    description: 'Network Management',
    url: 'https://unifi.local',
    iconName: 'Wifi',
    color: 'text-indigo-400',
    status: 'planned',
  },
  {
    id: 'adguard',
    name: 'AdGuard Home',
    description: 'Network Security',
    url: 'http://adguard.local',
    iconName: 'Shield',
    color: 'text-green-400',
    status: 'planned',
  },
  {
    id: 'homeassistant',
    name: 'Home Assistant',
    description: 'Home Automation',
    url: 'http://homeassistant.local',
    iconName: 'Home',
    color: 'text-blue-400',
    status: 'planned',
  },
];

export const INTERNAL_TOOLS: InternalTool[] = [
  // --- Workbench ---
  {
    id: 'fleet-log',
    name: 'Fleet Log',
    description: 'Vehicle & Home Maintenance Tracker',
    path: '/tools/fleet',
    iconName: 'ClipboardList',
    color: 'text-blue-400',
    category: 'workbench',
    status: 'active',
  },
  {
    id: 'pizza-calculator',
    name: 'Dough Math',
    description: 'Perfect pizza dough calculator',
    path: '/tools/pizza',
    iconName: 'Pizza',
    color: 'text-orange-400',
    category: 'workbench',
    status: 'active',
  },
  {
    id: 'brew-master',
    name: 'Brew Master',
    description: 'Homebrewing recipe builder',
    path: '/tools/brewing',
    iconName: 'Beer',
    color: 'text-amber-400',
    category: 'workbench',
    status: 'active',
  },
  // --- Web Development ---
  {
    id: 'bc-color-manager',
    name: 'BC Color Manager',
    description: 'BigCommerce Option Automation',
    path: '/tools/bc-colors',
    iconName: 'Palette',
    color: 'text-pink-400',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'utm-generator',
    name: 'UTM Generator',
    description: 'Campaign Link Builder',
    path: '/tools/utm-generator',
    iconName: 'Link2',
    color: 'text-violet-400',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'squoosh',
    name: 'Squoosh',
    description: 'Image Compression Tool',
    externalUrl: 'https://squoosh.app/',
    iconName: 'Minimize2',
    color: 'text-pink-500',
    category: 'web-dev',
    status: 'active',
  },
  {
    id: 'ai-upscaler',
    name: 'AI Upscaler',
    description: 'Enhance & Upscale Images',
    externalUrl: 'https://image-upscaling.net/upscaling/en.html',
    iconName: 'Maximize2',
    color: 'text-blue-500',
    category: 'web-dev',
    status: 'active',
  },
];